# Generated by Django 4.2.1 on 2023-06-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scallium_id', models.UUIDField()),
                ('is_moderated', models.BooleanField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['scallium_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scallium_id', models.UUIDField()),
                ('sellable', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_offers',
                'ordering': ['scallium_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOfferQuantities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.productoffer')),
            ],
            options={
                'db_table': 'product_offer_quantities',
                'default_related_name': 'quantities',
            },
        ),
        migrations.CreateModel(
            name='ProductOfferPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.productoffer')),
            ],
            options={
                'db_table': 'product_offer_prices',
                'default_related_name': 'prices',
            },
        ),
        migrations.CreateModel(
            name='ProductOfferAvailabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.productoffer')),
            ],
            options={
                'db_table': 'product_offer_availabilities',
                'default_related_name': 'availabilities',
            },
        ),
    ]
